/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proctor_diary;

import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.CMYKColor;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Properties;
import java.util.regex.Pattern;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Nilansh Thakur
 */
public class parentinteract_hod extends javax.swing.JFrame {

    /** Creates new form parentinteract_hod */
    public static  int selectInternal;
    public static  int selectSemester;
    public parentinteract_hod() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        showdate();
        showtime();
    }
    public void showdate(){
        java.util.Date d=new java.util.Date();
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy");
        datevar1.setText(s.format(d));
    }
    public void showtime(){
        new Timer(0,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                java.util.Date d=new java.util.Date();
                SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
                timevar.setText(s.format(d));
            }
        }).start();    
    }
    public static boolean isValid(String email) 
    { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_parent = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        datevar1 = new javax.swing.JLabel();
        timevar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        father_name = new javax.swing.JLabel();
        mother_name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        choose = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messagetoparentss = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        usnno = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        curr = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        guardian_name = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        subject1 = new javax.swing.JTextField();
        fnumber = new javax.swing.JLabel();
        mnumber = new javax.swing.JLabel();
        gnumber = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        setSize(new java.awt.Dimension(1500, 1500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        student_parent.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        student_parent.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(student_parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 653, 79));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 204));
        jLabel15.setText("Date:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 40, 100, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("Time:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 110, 80, 40));

        datevar1.setBackground(new java.awt.Color(0, 0, 0));
        datevar1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        datevar1.setForeground(new java.awt.Color(0, 204, 204));
        datevar1.setText("Date:");
        getContentPane().add(datevar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 30, 230, 40));

        timevar.setBackground(new java.awt.Color(0, 0, 0));
        timevar.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        timevar.setForeground(new java.awt.Color(0, 204, 204));
        timevar.setText("Time:");
        getContentPane().add(timevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 100, 220, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("FATHER'S NAME:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 220, 51));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("MOTHER'S NAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 220, 51));

        father_name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        father_name.setForeground(new java.awt.Color(0, 153, 204));
        getContentPane().add(father_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 351, 51));

        mother_name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mother_name.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(mother_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 351, 51));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SEND MAIL TO PARENTS:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 290, 56));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("CREATE");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 650, 137, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Create PDF of Student's Internal Marks & Attendance");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 650, 481, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("VIEW PDF");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 700, 139, 49));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 51));
        jLabel6.setText("Create PDF of Student's Current SEMESTER's SGPA and CGPA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 790, -1, 43));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("CREATE");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 790, 137, 43));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 51, 51));
        jButton4.setText("VIEW PDF");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 840, 152, 45));

        choose.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        choose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Father", "Mother", "Guardian", "All" }));
        getContentPane().add(choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 130, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("Attach Internal Marks PDF");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 510, 230, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("Attach Semester Grade PDF");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 580, 230, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 51, 51));
        jButton5.setText("ATTACH");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 520, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 51, 51));
        jButton6.setText("ATTACH");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 580, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setText("Enter Message to Send:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 740, 210, 50));

        messagetoparentss.setBackground(new java.awt.Color(0, 0, 0));
        messagetoparentss.setColumns(20);
        messagetoparentss.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        messagetoparentss.setForeground(new java.awt.Color(255, 255, 255));
        messagetoparentss.setRows(5);
        jScrollPane2.setViewportView(messagetoparentss);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 720, 410, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 153, 153));
        jButton7.setText("SEND");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 910, 180, 70));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 153, 153));
        jButton8.setText("BACK");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 910, 180, 70));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("USN:");

        usnno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usnno.setForeground(new java.awt.Color(0, 153, 153));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 255));
        jLabel11.setText("Current Semester");

        curr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        curr.setForeground(new java.awt.Color(0, 153, 153));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("STUDENT'S DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(curr, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usnno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usnno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("GUARDIAN'S NAME:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 220, 51));

        guardian_name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        guardian_name.setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().add(guardian_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 351, 47));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("SUBJECT:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 89, 25));

        subject1.setBackground(new java.awt.Color(0, 0, 0));
        subject1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        subject1.setForeground(new java.awt.Color(255, 255, 255));
        subject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject1ActionPerformed(evt);
            }
        });
        getContentPane().add(subject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 640, 280, 46));

        fnumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fnumber.setForeground(new java.awt.Color(0, 204, 204));
        fnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(fnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 300, 30));

        mnumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mnumber.setForeground(new java.awt.Color(0, 204, 204));
        mnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(mnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 300, 30));

        gnumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gnumber.setForeground(new java.awt.Color(0, 153, 153));
        gnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(gnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 300, 30));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 0));
        jLabel19.setText("FATHER:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 0));
        jLabel20.setText("MOTHER:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 0));
        jLabel21.setText("GUARDIAN:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("PHONE NUMBERS:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 220, 48));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                            Font blueFont = FontFactory.getFont(FontFactory.HELVETICA, 17, Font.NORMAL, new CMYKColor(255, 0, 0, 0));
                            Font redFont = FontFactory.getFont(FontFactory.COURIER, 22, Font.BOLD, new CMYKColor(0, 255, 0, 0));
                            Font cyanFont = FontFactory.getFont(FontFactory.COURIER, 20, Font.BOLD, new CMYKColor(3, 252, 211,0));
                            Font bluishFont = FontFactory.getFont(FontFactory.COURIER, 18, Font.BOLD, new CMYKColor(3, 194, 252,0));
                            Font orangeFont = FontFactory.getFont(FontFactory.COURIER, 16, Font.BOLD, new CMYKColor(252, 173, 3,0));                   
        try{                String usn=usnno.getText();
                            
                            Document dc=new Document();
                            int curr1=Integer.parseInt(curr.getText());
                            Class.forName("com.mysql.jdbc.Driver");
                           Connection con = DriverManager.getConnection("jdbc:mysql://bykqcbjckqhrun54vgmr-mysql.services.clever-cloud.com:3306/bykqcbjckqhrun54vgmr","uu799vkgk1pcx35b","Hqy3pqsIAdaAt6gMuPNe");
                            String query="select * from internalmarks";
                            PreparedStatement ps=con.prepareStatement(query);
                            ResultSet rs=ps.executeQuery();
                            PdfWriter.getInstance(dc, new FileOutputStream("D:\\"+usn+"_internalMarks.pdf"));
                            dc.open();
                            String welcome="                        "+usn+" 'S INTERNAL MARKS FOR "+curr1+" SEMESTER:";
                            dc.add(new Paragraph(welcome,redFont));
                            for( int i=0;i<6;i++){
                                    dc.add(new Paragraph(" "));
                                }
                            dc.add(new Paragraph("                   INTERNAL MARKS(COURSE CODE WISE)",cyanFont));
                            for( int i=0;i<3;i++){
                                    dc.add(new Paragraph(" "));
                                }
                            dc.add(new Paragraph("COURSE CODE       COURSE NAME            MARKS       SEMESTER       INTERNAL NUMBER",bluishFont));
                            while(rs.next()){
                                String usn1=rs.getString("usnno");
                                int cur=rs.getInt("sem");
                                if(usn1.equals(usn) && curr1==cur){
                                    dc.add(new Paragraph(rs.getString("course_code")+"        "+rs.getString("course_name")+"             "+rs.getInt("marks")+"        "+rs.getInt("sem")+"        "+rs.getInt("internalno"),blueFont));
                                    dc.add(new Paragraph(" "));    
                                }
                            }
                            rs.close();
                            for( int i=0;i<3;i++){
                                    dc.add(new Paragraph(" "));
                                }
                            dc.add(new Paragraph("                   ATTENDANCE(COURSE CODE WISE)",cyanFont));
                            for( int i=0;i<3;i++){
                                    dc.add(new Paragraph(" "));
                                }
                            String query1="select * from student_attendance";
                            PreparedStatement ps1=con.prepareStatement(query1);
                            ResultSet rs1=ps1.executeQuery();
                            dc.add(new Paragraph("COURSE CODE       DATE MODIFIED       ATTENDANCE       TOTAL_ATTENDANCE       SEMESTER",blueFont));
                            while(rs1.next()){
                                String usn1=rs1.getString("usnno");
                                int cur=rs1.getInt("current_sem");
                                if(usn1.equals(usn) && curr1==cur){
                                    dc.add(new Paragraph(rs1.getString("course_code")+"       "+rs1.getString("course_name")+"            "+rs1.getInt("marks")+"        "+rs1.getInt("sem")+"        "+rs1.getInt("internalno"),orangeFont));
                                    dc.add(new Paragraph(" "));    
                                }
                            }
                            rs1.close();
                            dc.close();
                            JOptionPane.showMessageDialog(null,"PDF Created! Please view before sending it to the Parent");
          }catch(SQLException e){
                                System.err.println("The details have not been entered yet");
                                JOptionPane.showMessageDialog(null,"The details have not been entered yet");
                            }
        catch(Exception e){
                                System.err.println(e);
                                JOptionPane.showMessageDialog(null,e);
                            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"D:\\"+usnno.getText()+"_SemesterEndGrade.pdf");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
    }    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"D:\\"+usnno.getText()+"_internalMarks.pdf");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                            Font blueFont = FontFactory.getFont(FontFactory.HELVETICA, 17, Font.NORMAL, new CMYKColor(255, 0, 0, 0));
                            Font redFont = FontFactory.getFont(FontFactory.COURIER, 22, Font.BOLD, new CMYKColor(0, 255, 0, 0));
                            Font cyanFont = FontFactory.getFont(FontFactory.COURIER, 20, Font.BOLD, new CMYKColor(3, 252, 211,0));
                            Font bluishFont = FontFactory.getFont(FontFactory.COURIER, 18, Font.BOLD, new CMYKColor(3, 194, 252,0));
                            Font orangeFont = FontFactory.getFont(FontFactory.COURIER, 16, Font.BOLD, new CMYKColor(252, 173, 3,0));                   
        try{                String usn=usnno.getText();
                            Document dc=new Document();
                            int curr1=Integer.parseInt(curr.getText());
                            Class.forName("com.mysql.jdbc.Driver");
                           Connection con = DriverManager.getConnection("jdbc:mysql://bykqcbjckqhrun54vgmr-mysql.services.clever-cloud.com:3306/bykqcbjckqhrun54vgmr","uu799vkgk1pcx35b","Hqy3pqsIAdaAt6gMuPNe");
                            String query="select * from result";
                            PreparedStatement ps=con.prepareStatement(query);
                            ResultSet rs=ps.executeQuery();
                            PdfWriter.getInstance(dc, new FileOutputStream("D:\\"+usn+"_SemesterEndGrade.pdf"));
                            dc.open();
                            String welcome="                        "+usn+" 'S SEMESTER GRADE FOR "+curr1+" SEMESTER:";
                            dc.add(new Paragraph(welcome,redFont));
                            for( int i=0;i<6;i++){
                                    dc.add(new Paragraph(" "));
                                }
                            dc.add(new Paragraph("                   SEMESTER GRADE MARKS",cyanFont));
                            for( int i=0;i<3;i++){
                                    dc.add(new Paragraph(" "));
                                }
                            dc.add(new Paragraph("CGPA       SGPA       SEMESTER       BACKLOGS       FASTRACK",bluishFont));
                            while(rs.next()){
                                String usn1=rs.getString("usn");
                                int cur=rs.getInt("r_sem");
                                if(usn1.equals(usn) && curr1==cur){
                                    dc.add(new Paragraph(rs.getString("cgpa")+"       "+rs.getString("sgpa")+"            "+rs.getString("r_sem")+"        "+rs.getInt("backlogs")+"        "+rs.getString("fastrack"),blueFont));
                                    dc.add(new Paragraph(" "));    
                                }
                            }
                            rs.close();
                            dc.close();
                            JOptionPane.showMessageDialog(null,"PDF Created! Please view before sending it to the Parent");
          }catch(SQLException e){
                                System.err.println("The details have not been entered yet");
                                JOptionPane.showMessageDialog(null,"The details have not been entered yet");
                            }
        catch(Exception e){
                                System.err.println(e);
                                JOptionPane.showMessageDialog(null,e);
                            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        selectInternal=1;
        JOptionPane.showMessageDialog(null,"You have chosen to attach file :"+"D:\\"+usnno.getText()+"_internalMarks.pdf");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        selectSemester=1;
        JOptionPane.showMessageDialog(null,"You have chosen to attach file :"+"D:\\"+usnno.getText()+"_SemesterEndGrade.pdf");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
            String selected=choose.getSelectedItem().toString();
            String emailtosend="";
            int c=0;
            String usn1=usnno.getText();
            Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://bykqcbjckqhrun54vgmr-mysql.services.clever-cloud.com:3306/bykqcbjckqhrun54vgmr","uu799vkgk1pcx35b","Hqy3pqsIAdaAt6gMuPNe");
            String query="select * from parent_email";
            PreparedStatement ps=con.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                String usn=rs.getString("usnno");
                if(usn.equals(usn1)){
                    if(selected=="Father"){
                        emailtosend=rs.getString("father_email");
                    }else if(selected=="Mother"){
                        emailtosend=rs.getString("mother_email");
                    }else if(selected=="Guardian"){
                        emailtosend=rs.getString("guardian_email");
                    }else{
                        c=1;
                        emailtosend=rs.getString("father_email");
                        emailtosend=emailtosend+"\n"+rs.getString("mother_email");
                        emailtosend=emailtosend+"\n"+rs.getString("guardian_email");
                    }
                }
            }
            String fromemail="proctordiarymanagement2019@gmail.com";
                    String fromemailpassword="Proctor@123";
                    String subject="HOD of your ward: "+usnno.getText()+" has sent a message. SUBJECT-"+subject1.getText();
                    String emailmessage=messagetoparentss.getText();
                    Properties properties=new Properties();
                    properties.put("mail.smtp.auth","true");
                    properties.put("mail.smtp.starttls.enable","true");
                    properties.put("mail.smtp.host","smtp.gmail.com");
                    properties.put("mail.smtp.port","587");

                    Session session=Session.getDefaultInstance(properties,new javax.mail.Authenticator(){
                    @Override
                    protected PasswordAuthentication getPasswordAuthentication(){
                        return new PasswordAuthentication(fromemail,fromemailpassword);
                    }
                    });

                    try{
                        int attachboth=0;
                        MimeBodyPart attachPart=new MimeBodyPart();
                        MimeBodyPart attachPart1=new MimeBodyPart();
                        Multipart multipart = new MimeMultipart();
                        String attachFile="";
                        if(selectInternal==1){
                            attachFile="D:\\"+usnno.getText()+"_internalMarks.pdf";
                        }
                        if(selectSemester==1){
                            attachFile="D:\\"+usnno.getText()+"_SemesterEndGrade.pdf";
                        }
                        if(selectSemester==1 && selectInternal==1){
                            attachboth=1;
                            String atttachFile="D:\\"+usnno.getText()+"_internalMarks.pdf";
                            String atttachFile2="D:\\"+usnno.getText()+"_SemesterEndGrade.pdf";
                            attachPart.attachFile(atttachFile);
                            multipart.addBodyPart(attachPart);
                            attachPart1.attachFile(atttachFile2);
                            multipart.addBodyPart(attachPart1);
                        }else{
                        attachPart.attachFile(attachFile);
                        multipart.addBodyPart(attachPart);
                        }
                        MimeMessage message=new MimeMessage(session);
                        message.setFrom(new InternetAddress(fromemail));
                        String[] toemail;
                        if(selected=="Father" || selected=="Mother"|| selected=="Guardian"){
                            message.addRecipient(Message.RecipientType.TO, new InternetAddress(emailtosend));
                        }
                        if(selected=="All"){
                            toemail=emailtosend.split("\n");
                        
                        for(int i=0;i<toemail.length;i++){
                             message.addRecipient(Message.RecipientType.TO, new InternetAddress(toemail[i]));
                        }
                        }
                        //message.addRecipient(Message.RecipientType.TO, new InternetAddress(toemail[i]));
                        message.setSubject(subject);
                        message.setText(emailmessage);
                        message.setContent(multipart);
                        Transport.send(message);
                    }catch(Exception e){
                        System.out.println(""+e);
                        JOptionPane.showMessageDialog(null,e);
                    }
        }catch(Exception e){
            System.out.println(""+e);
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parentinteract_hod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parentinteract_hod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parentinteract_hod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parentinteract_hod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parentinteract_hod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> choose;
    public javax.swing.JLabel curr;
    private javax.swing.JLabel datevar1;
    public javax.swing.JLabel father_name;
    public javax.swing.JLabel fnumber;
    public javax.swing.JLabel gnumber;
    private javax.swing.JLabel guardian_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messagetoparentss;
    public javax.swing.JLabel mnumber;
    public javax.swing.JLabel mother_name;
    public javax.swing.JLabel student_parent;
    public javax.swing.JTextField subject1;
    private javax.swing.JLabel timevar;
    public javax.swing.JLabel usnno;
    // End of variables declaration//GEN-END:variables

}
